dev.driverClassName=com.mysql.cj.jdbc.Driver
dev.url=jdbc:mysql://localhost:3306/db_imperial_court?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
dev.username=root
dev.password=445566hh
dev.initialSize=10
dev.maxActive=20
dev.maxWait=10000